import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Icon } from '@iconify/react';
import Link from 'next/link'

const EditBook: NextPage = ( allBooks ) => {
  return (
    <div  style={{  
      backgroundImage: "url(/bg.png)",
      backgroundPosition: 'center',
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
    }}>
      <Head>
        <title >Llibre</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex flex-col h-screen py-20">
       
        <section className='w-6/12 mx-auto'>

        <div className='flex items-center '>
          <Link href={`/`}>
            <Icon icon="akar-icons:arrow-back" className='bg-white  invisible sm:visible rounded-full p-2 h-8 w-8 text-amber-800 text-xl transition ease-in-out hover:scale-110 hover:cursor-pointer' />
          </Link>
          <h1 className="font-bold mx-auto text-4xl bg-white  text-amber-800 py-4 px-12  rounded-2xl">
                {allBooks.data.title}
          </h1>
        </div>

          <div className='grid grid-cols-1  gap-6 my-10 bg-white p-6 rounded-lg '>

            
            <div className='flex flex-col bg-gray-200 gap-y-2 rounded-lg transition ease-in-out hover:scale-105'>
              <div className='w-full h-64 bg-gray-400 rounded-t-lg'>Image</div>
              <div id="bookInfo" className='grid gap-y-2 px-4 py-2 text-xl '>
                <div className='flex place-content-between text-amber-800'>
                  <h2 className='text-amber-800'>{allBooks.data.title}</h2>
                  <Icon icon="akar-icons:edit" className='h-8 w-8  transition ease-in-out hover:scale-110 hover:cursor-pointer' />
                </div>
                <h3 className='text-xl'>Autor: {allBooks.data.author}</h3>
                <p>Descripció: {allBooks.data.description}</p>
                <p>Preu: {allBooks.data.price} €</p>
              </div>
            </div>

          
            
          </div>
        
          

         
        </section>   
      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default EditBook

export async function  getServerSideProps({query}) {
  const response = await fetch(`http://localhost:3000/api/book?id=${query.id}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      },
  })
  const data = await response.json()
  return {
    props: { data }
  }

}

