import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = ( allBooks ) => {
  return (


    <div className={styles.container}>
      <Head>
        <title >Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col h-screen py-20">
        <h1 className=" mx-auto font-bold  text-4xl text-[#0070f3]">
              Llistat de llibres
        </h1>
        <section className='w-8/12 mx-auto'>

         

          <div className='grid grid-cols-1 md:grid-cols-3 gap-4 my-10 border-gray-200 border-2 border-r-4 p-4'>

            { allBooks.data.map((book) => (
                <div className='flex flex-col bg-gray-200 gap-y-2' key={book.id}>
                  <div className='w-64 h-64 bg-gray-400'>Image</div>
                  <h2 className='text-blue-500 text-2xl'>{book.title}</h2>
                  <h3 className='text-xl'>{book.author}</h3>
                  <p>{book.description}</p>
                  <p>{book.price}</p>
                </div>

            ))}
            
          </div>
        
          

         
        </section>   
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export async function getStaticProps() {
  
  const response = await fetch('http://localhost:3000/api/list_all')
  const data = await response.json()
  console.log(data);
  return {
    props: { data }
  }

}
