import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Icon } from '@iconify/react';
import Link from 'next/link'

const Home: NextPage = ( allBooks ) => {
  return (


    <div className={styles.container} style={{  
      backgroundImage: "url(/bg.png)",
      backgroundPosition: 'center',
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
    }}
    
    >
      <Head>
        <title >Llibres</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex flex-col h-screen py-20">
        <h1 className=" mx-auto font-bold  text-4xl bg-white text-amber-800 py-4 px-12  rounded-2xl">
              Llistat de llibres
        </h1>
        <section className='w-8/12 mx-auto'>

         

          <div className='grid grid-cols-1 md:grid-cols-2 gap-6 my-10 bg-white p-6 rounded-lg '>

            { allBooks.data.map((book) => (
                <div className='flex flex-col bg-gray-200 gap-y-2 rounded-lg transition ease-in-out hover:scale-105' key={book.id}>
                  <div className='w-full h-64 bg-gray-400 rounded-t-lg'>Image</div>
                  <div id="bookInfo" className='grid gap-y-2 px-4 py-2 text-xl '>
                    <div className='flex place-content-between text-amber-800'>
                      <h2 className='text-amber-800'>{book.title}</h2>
                      <Link href={`edit/${book.id}`}>
                        <Icon icon="akar-icons:info" className='h-8 w-8  transition ease-in-out hover:scale-110 hover:cursor-pointer' />
                      </Link>
                    </div>
                    <h3 className='text-xl'>Autor: {book.author}</h3>
                    <p>Descripció: {book.description}</p>
                    <p>Preu: {book.price} €</p>
                  </div>
                </div>

            ))}
            
          </div>
        
          

         
        </section>   
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export async function getStaticProps() {
  
  const response = await fetch('http://localhost:3000/api/list_all', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      },
  })
  const data = await response.json()
  return {
    props: { data }
  }

}
